# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: LicenseRef-Intel

# Default values for all Helm charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  fullnameOverride: "onos"
  nameOverride: ""
  image:
    registry: ""
    tag: ""
  atomix:
    store:
      consensus:
        enabled: true
        name: ""
        image:
          registry: ""
          repository: atomix/consensus-node
          tag: ""
          pullPolicy: ""
          pullSecrets: []
        replicas: 3
        partitions: 30
        config:
          server: {}
          raft: {}
          logging:
            loggers:
              root:
                level: info
                output:
                  stdout:
                    sink: stdout
            sinks:
              stdout:
                stdout: {}
        log:
          storageClass: ""
          resources:
            requests:
              storage: 1Gi
        securityContext: {}

import:
  onos-topo:
    enabled: true
  onos-config:
    enabled: true
  onos-cli:
    enabled: true
  roc-api:
    enabled: true
  roc-gui:
    enabled: true
  roc-adapter:
    enabled: true

# ONOS-CLI
onos-cli: {}

# ROC API
roc-api:
  image:
    registry: default-route-openshift-image-registry.apps.nex.one-edge.intel.com
    repository: springboard-dev-common/roc-api-server-sca-0.1.x
    tag: 0.1.2-dev
    pullPolicy: IfNotPresent
# for GUI development only - comment out for production
#  corsOrigins:
#    - http://localhost:3000

roc-adapter:
  fullnameOverride: "roc-adapter"
  certManager:
    enabled: false
  image:
    registry: default-route-openshift-image-registry.apps.nex.one-edge.intel.com
    repository: springboard-dev-common/roc-adapter-sca-0.1.x
    tag: 0.1.2-dev
    pullPolicy: IfNotPresent

roc-gui:
  service:
    name: roc-gui
    port: 8081
    type: NodePort
    nodePort: 30002
  runtimeConfig:
    targetType: city
  image:
    registry: default-route-openshift-image-registry.apps.nex.one-edge.intel.com
    repository: springboard-dev-common/roc-ui
    tag: v0.2.3
    pullPolicy: IfNotPresent

# ONOS-TOPO
onos-topo:
  atomix:
    store:
      consensus:
        enabled: false

# ONOS-CONFIG
onos-config:
  atomix:
    store:
      consensus:
        enabled: false
  modelPlugins:
    - name: sca-0-1-x
      image: default-route-openshift-image-registry.apps.nex.one-edge.intel.com/springboard-dev-common/roc-model-sca-0.1.x:0.1.2-dev
      pullPolicy: IfNotPresent
      endpoint: localhost
      port: 5152

  openpolicyagent:
    enabled: false
    regoConfigMap: fabric-umbrella-opa-rbac


topology:
  kinds:
    - kind: city
  adapter:
    address: roc-adapter:5150
    version: 0.1.x
    type: sca
  targets:
    - id: reference-city
      name: Reference City
      kind: city

# Load Initial Mega-Patch
config:
  reconcile_interval: 30s
  # Path to the mega-patch json file
  megaPatch: ""
  image:
    registry: ""
    repository: curlimages/curl
    tag: "7.85.0"
    pullPolicy: "IfNotPresent"
